version: '3'

services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

  flask-app:
    build: ./flask_app  # Path to your Flask app directory
    ports:
      - 5001:5001
    depends_on:
      - mongodb  # Wait for MongoDB to be ready before starting the Flask app
    environment:
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=password
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017

